name: widgetbook_workspace
description: "Flutter widget book"
publish_to: 'none'
version: 0.1.1
resolution: workspace

environment:
  sdk: ">=3.9.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  analog_clock_widget:
    path: ../analog_clock_widget
  animated_checkbox_widget:
    path: ../animated_checkbox_widget
  extensions:
    path: ../extensions
  theme_manager:
    path: ../theme_manager

dev_dependencies:
  build_runner: ^2.7.0   # dart run build_runner build --delete-conflicting-outputs
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  widgetbook_generator: ^3.20.1
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

flutter:
  uses-material-design: true
