# pubspec.yaml
name: example_editor
description: Smoke test for edittext_popover package.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.35.5"

dependencies:
  edittext_popover:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true