name: splash_screen_package
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

