# pubspec.yaml - extensions
name: extensions
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.9.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true